"use client";

import React from "react";
import { cn } from "@/lib/utils";
import { useApp } from "../../context/AppContext";

interface OfficialPrintWrapperProps {
  title: string;
  subtitle?: React.ReactNode;
  metadata?: React.ReactNode;
  orientation?: "portrait" | "landscape";
  children: React.ReactNode;
  showSignatures?: boolean;
  leftSignatureTitle?: string;
  centerSignatureTitle?: string;
  rightSignatureTitle?: string;
  showSystemFooter?: boolean;
}

const OfficialPrintWrapper = ({
  title,
  subtitle,
  metadata,
  orientation = "portrait",
  children,
  showSignatures = true,
  leftSignatureTitle,
  centerSignatureTitle,
  rightSignatureTitle,
  showSystemFooter = true
}: OfficialPrintWrapperProps) => {
  const { t, isRTL, institution } = useApp();

  const finalLeftTitle = leftSignatureTitle || (isRTL ? "المدير" : "Director");
  const finalCenterTitle = centerSignatureTitle || institution.pedagogicalManagerTitle || (isRTL ? "المسؤول البيداغوجي" : "Pedagogical Manager");
  const finalRightTitle = rightSignatureTitle || (isRTL ? "أستاذ الفرع" : "Branch Teacher");

  return (
    <div 
      className={cn(
        "bg-white mx-auto page-break-container relative",
        orientation === "portrait" ? "md:w-[210mm]" : "md:w-[297mm]",
        "print:w-full print:p-0 print:mb-0"
      )}
      dir={isRTL ? "rtl" : "ltr"}
    >
      {/* Header with Logo */}
      <div className="flex justify-between items-start mb-4 print:mb-2">
        <div className="w-24 h-24 flex items-center justify-center border-2 border-emerald-900/10 rounded-2xl p-2">
          {/* Placeholder for Logo - In a real app, this would be institution.logo */}
          <div className="w-full h-full bg-emerald-50 rounded-xl flex items-center justify-center text-emerald-800 font-black text-[10px] text-center uppercase">
            Logo
          </div>
        </div>

        <div className="flex-1 text-center space-y-1">
          <h2 className="font-black text-emerald-950 text-xl md:text-2xl">{institution.name}</h2>
          <h3 className="font-bold text-emerald-700 text-lg">{title}</h3>
          {subtitle && <div className="text-emerald-600 font-bold text-sm">{subtitle}</div>}
        </div>

        <div className="w-24"></div> {/* Spacer for symmetry */}
      </div>

      {/* Metadata Bar */}
      {metadata && (
        <div className="border-y-2 border-emerald-900/20 py-2 mb-4 flex justify-between items-center text-xs font-black text-emerald-900 print:mb-2">
          {metadata}
        </div>
      )}

      {/* Main Content */}
      <div className="w-full overflow-hidden mb-6">
        {children}
      </div>

      {/* Signatures Footer */}
      {showSignatures && (
        <div className="grid grid-cols-3 gap-8 pt-4 border-t-2 border-emerald-900/10">
          <div className="text-center">
            <p className="font-black text-emerald-950 text-xs mb-1">{finalRightTitle}</p>
            <div className="h-16 border border-dashed border-emerald-200 rounded-xl mt-1"></div>
          </div>
          <div className="text-center">
            <p className="font-black text-emerald-950 text-xs mb-1">{finalCenterTitle}</p>
            <div className="h-16 border border-dashed border-emerald-200 rounded-xl mt-1"></div>
          </div>
          <div className="text-center">
            <p className="font-black text-emerald-950 text-xs mb-1">{finalLeftTitle}</p>
            <div className="h-16 border border-dashed border-emerald-200 rounded-xl mt-1"></div>
          </div>
        </div>
      )}

      {showSystemFooter && (
        <div className="mt-4 text-center text-[8px] font-bold text-slate-300 uppercase tracking-widest border-t border-slate-50 pt-2 print:hidden">
          Generated by EduSchedule Pro
        </div>
      )}
    </div>
  );
};

export default OfficialPrintWrapper;