"use client";

import React from "react";
import { cn } from "@/lib/utils";
import { useApp } from "../../context/AppContext";

interface OfficialPrintWrapperProps {
  title: string;
  subtitle?: React.ReactNode;
  metadata?: React.ReactNode;
  orientation?: "portrait" | "landscape";
  children: React.ReactNode;
  showSignatures?: boolean;
  leftSignatureTitle?: string;
  centerSignatureTitle?: string;
  rightSignatureTitle?: string;
  showSystemFooter?: boolean;
}

const OfficialPrintWrapper = ({
  title,
  subtitle,
  metadata,
  orientation = "portrait",
  children,
  showSignatures = true,
  leftSignatureTitle,
  centerSignatureTitle,
  rightSignatureTitle,
  showSystemFooter = true
}: OfficialPrintWrapperProps) => {
  const { isRTL, institution } = useApp();

  const finalLeftTitle = leftSignatureTitle || (isRTL ? "المدير" : "Director");
  const finalCenterTitle = centerSignatureTitle || institution.pedagogicalManagerTitle || (isRTL ? "المسؤول البيداغوجي" : "Pedagogical Manager");
  const finalRightTitle = rightSignatureTitle || (isRTL ? "أستاذ الفرع" : "Branch Teacher");

  return (
    <div 
      className={cn(
        "bg-white mx-auto page-break-container relative",
        "px-[10mm] py-[10mm]",
        orientation === "portrait" ? "w-[210mm]" : "w-[297mm]",
        "shadow-none border-none"
      )}
      dir={isRTL ? "rtl" : "ltr"}
    >
      {/* Header */}
      <div className="flex justify-between items-start mb-4 print:mb-2">
        <div className="w-20 h-20 print:w-16 print:h-16 flex items-center justify-center border border-slate-200 rounded-xl p-2 print:border-black">
          <div className="w-full h-full bg-slate-50 flex items-center justify-center text-slate-400 font-bold text-[10px] print:bg-transparent print:text-black">
            LOGO
          </div>
        </div>

        <div className="flex-1 text-center">
          <h2 className="font-black text-slate-950 text-lg print:text-base print:text-black">{institution.name}</h2>
          <h3 className="font-bold text-emerald-700 text-base print:text-sm print:text-black">{title}</h3>
          {subtitle && <div className="text-emerald-600 font-bold text-xs print:text-[10px] print:text-black">{subtitle}</div>}
        </div>

        <div className="w-20 print:w-16"></div> 
      </div>

      {/* Metadata Bar */}
      {metadata && (
        <div className="border-y border-slate-200 py-1.5 mb-3 flex justify-between items-center text-[10px] font-black text-slate-600 print:border-black print:text-black print:mb-2">
          {metadata}
        </div>
      )}

      {/* Content */}
      <div className="w-full overflow-hidden mb-4 print:mb-2">
        {children}
      </div>

      {/* Signatures */}
      {showSignatures && (
        <div className="grid grid-cols-3 gap-4 pt-3 border-t border-slate-200 print:border-black print:pt-2">
          <div className="text-center">
            <p className="font-black text-slate-950 text-[10px] mb-1 print:text-black">{finalRightTitle}</p>
            <div className="h-12 border border-dashed border-slate-200 rounded-xl print:border-black"></div>
          </div>
          <div className="text-center">
            <p className="font-black text-slate-950 text-[10px] mb-1 print:text-black">{finalCenterTitle}</p>
            <div className="h-12 border border-dashed border-slate-200 rounded-xl print:border-black"></div>
          </div>
          <div className="text-center">
            <p className="font-black text-slate-950 text-[10px] mb-1 print:text-black">{finalLeftTitle}</p>
            <div className="h-12 border border-dashed border-slate-200 rounded-xl print:border-black"></div>
          </div>
        </div>
      )}

      {showSystemFooter && (
        <div className="mt-2 text-center text-[7px] font-bold text-slate-300 print:hidden">
          Generated by EduSchedule Pro
        </div>
      )}
    </div>
  );
};

export default OfficialPrintWrapper;